### ISSUE TITLE
qreg_example.jl don't run

### ISSUE THREAD

**Issue by JonWel** [pkofod/QuantileRegression.jl#11]
With `Julia 0.4.6` and `DataFrames 0.8.3` I get:

``` Julia
ERROR: LoadError: type CoefTable has no field mat
```

The definition has in deed changed: https://github.com/JuliaStats/StatsBase.jl/blob/master/src/statmodels.jl#L161

The access to the data seems to have to be done by `.cols` instead of `.mat`, with the difference of having a vector of columns instead of a matrix.

**Comment by pkofod** [comment]
Thank you for the report. I haven't really worked on this package for a year at least, but I see no reason why it shouldn't work. Would you have any interest in making a PR that fixes it?

**Comment by JonWel** [comment]
Just to be sure, when you have something like this:
```Julia
             Estimate   Std.Error   t value
(Intercept)  81.4823    14.6345      5.56783
income        0.560181   0.0131756  42.5164
```
The values selected with `.mat[2,1:2]` are `0.560181`  and  `0.0131756`?

**Comment by JonWel** [comment]
@pkofod By replacing these two lines, it runs:
```julia
DataPlot = reduce(vcat,[reduce(hcat,coeftable(qreg(foodexp ~ income, Data, i/(QNum+1))).cols[1:2])[2,:] for i in 1:QNum])
ols = repeat(reduce(hcat,coeftable(ResultLM).cols[1:2])[2,:],inner=[QNum,1])
```
However the dotted lines are not identical to the example:
![qreg_example_plot](https://cloud.githubusercontent.com/assets/11057909/18688209/962ba648-7f83-11e6-9d19-59861e492638.png)

This type of graphs are a bit new to me, so I'm hoping the example to help me understand how to use the library.
I thus prefer to be sure the corrections are done correctly (I don't think I can add such graphs to a PR).

If this is OK for you like this, I can do the PR.

**Comment by pkofod** [comment]
Just want to let you know that I have seen this, and I will have a look at it tomorrow. If I forget, please ping me!

**Comment by JonWel** [comment]
Ok, this graph may help you see the difference (seems Winston also changed in between):
![qreg_example_plot_supp2](https://cloud.githubusercontent.com/assets/11057909/18689078/9f3f28fa-7f87-11e6-87f5-96745498f558.png)

Black is the original one, red is the new.
And I have no Idea why it looks so close but these 4 points.

**Comment by vincentarelbundock** [comment]
Package is no longer supported. See amended README file.

**Comment by pkofod** [comment]
I'm not sure if you every found out @JonWel, but this seems to be because I changed the default to the interior point method. The point estimates differ a little, and that has the effect you see, because the standard errors are a bit sensitive the way we calculate them. I will have a look at it.

**Comment by JonWel** [comment]
@pkofod My concerns where more on the fact that I do not know enough on the statistical theories behind (I was counting on analysis the example to see if this was what I needed), so I was not sure if I was making anything wrong with my correction: I don't want to mess someone else's package.

After a better understanding thanks to the example, it turned out quantile regressions where not what I was needing for my project.
If you want me to do the PR with the corrections to the example I proposed, just tell me.

**Comment by pkofod** [comment]
I've got a working version in #13 but thank you for offering to help.
