### ISSUE TITLE
fix example on readme

### ISSUE THREAD

**Issue by floswald** [pkofod/QuantileRegression.jl#21]
and probably drop support for anything less than v0.6?

**Comment by floswald** [comment]
if not you'll have to undo my PR because i just ripped out the macro that switches the `qrfact` call on version. I think going v0.6 is the right thing to do at this point.

**Comment by pkofod** [comment]
Your line here https://github.com/pkofod/QuantileRegression.jl/pull/20/files#diff-58476995b642435595799e856c5d2a74R3 did that

**Comment by floswald** [comment]
sure, i know. i just thought you may want to mention it on the readme, but it's not first order.

**Comment by pkofod** [comment]
Ah, that it's no longer supported?

**Comment by pkofod** [comment]
example is fixed, thanks
