### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tbeason** [pkofod/QuantileRegression.jl#23]
The package currently doesn't even precompile.  `DataFrameRegressionModel` has been moved to `RegressionModel` in StatsModels.jl and that is the main issue as far as I can tell. I'm sure there will be some other things to tackle beyond just that.

Would be good to get this up to speed with Julia v0.6.2 & v0.7.

**Comment by pkofod** [comment]
Yes that would be great. I see @alancrawford has recently forked and made some deprecation fixes, so I'm bringing hm into the conversation.

**Comment by tbeason** [comment]
I'll let this sit a few more days before I duplicate his work.

**Comment by mcreel** [comment]
In my tree, InteriorPoint.jl works with v0.6.x, in case that's helpful.

**Comment by alancrawford** [comment]
Sorry for the delay in coming back on this. I issued a PR here #25 for a few deprecations and patched it up for DataFrames v0.11. Though it probably should be looked at by someone more familiar with the recent developments StatsModels and DataFrames packages.

In terms of further changes, I wondered about adopting a similar syntax and output developed in the `https://github.com/matthieugomez/FixedEffectModels.jl` package with something like this:

```
using DataFrames, RDatasets, FixedEffectModels
df = dataset("plm", "Cigar")
qreg(df, @model(Sales ~ NDI, quantile = 0.5)) 
```
My (potentially flawed) logic is that there may be some benefits for users to face similar syntax across packages in which they might be interested. Thoughts?

**Comment by mcreel** [comment]
In my opinion, methods should use a syntax as plain and simple as possible, and then someone can put together a frontend with a uniform syntax, much like Plots.jl does for plotting. Supporting DataFrames as the input is fine, but requiring it would be confining. At some point, when the backend tools are ready, a nice frontend for econometric and statistical models would be a great package.

**Comment by pkofod** [comment]
If the syntax can be something that maps *down* to our syntax it could be interesting in a high level package for econometrics as @mcreel mentions, but given the activity on this repo, I don't feel duplicating efforts is a good idea, but maybe their `@model` code could be refactored into a separate package that could then be used for this pkg as well?
